config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # root
  root 'shops#index'

  # # redirect
  # get '/reviews' => redirect('/reviews/new')

  # google login
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i(create destroy)

  # mypage
  get 'mypage', to: 'users#mypage', as: :mypage

  # all shops
  get 'all', to: 'shops#all', as: :all_shops

  # search form page
  get 'search_form', to: 'shops#search_form', as: :search_form

  # search
  get 'search', to: 'shops#search', as: :search

  # new shop results page
  get 'new_shop_result', to: 'shops#new_shop_results', as: :new_shop_results

  # new shop form
  get 'new_form', to: 'shops#new_form', as: :new_form

  # add new shop & show shop detail
  resources :shops, only: %i(create show) do
    collection do
      get :search_result
    end
  end

  # new review form & add new review & delete review
  resources :reviews, only: %i(new create destroy)

  # wants list page
  resources :users do
    resources :wants, except: %i(edit show update)
  end
end

app/models/want.rb
class Want < ApplicationRecord
  # relation
  belongs_to :user

  # validation
  validates :shop_name, :address,
            presence: true
  validates :shop_name,
            length: { maximum: 50 }
  validates :address,
            format: { with: /.*[都道府県]/ }
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  before_action :init_want
  before_action :find_user

  def new
  end

  def create
    @want = @user.wants.new(want_params)

    if @want.save
      redirect_to user_wants_path(@user), notice: 'リストに追加しました'
    else
      render 'new'
    end
  end

  def destroy
    want = Want.find(params[:id])
    want.destroy

    redirect_to user_wants_path(@user)
  end


  private
  def want_params
    params.require(:want).permit(:shop_name, :address, :memo)
  end

  def init_want
    @want = Want.new
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/wants_helper.rb
module WantsHelper
end

app/views/wants/index.html.erb
  <div id="main-content">
    <!-- menu -->
    <%= render 'partial/menu' %>

    <!-- wants list -->
    <section class="mt-5">
      <h1 class="text-red-500 font-bold text-xl inline">行きたいお店リスト</h1>
      <%= link_to new_user_want_path(current_user), class: 'bg-red-600 text-white px-2 py-1 rounded mt-5 inline-block ml-2' do %>
      <span class="material-icons" style="vertical-align: -7px;">
        add
      </span>
      お店を追加
      <% end %>
      <div class="w-full sm:w-1/2 md:w-1/3 mb-4 mt-5 px-2">
        <% if current_user.wants.exists? %>
        <% current_user.wants.each do |want| %>
        <div class="relative bg-white rounded border my-3">
          <div class="p-4">
            <h3 class="text-lg font-bold">
              <a class="stretched-link" href="#" title="Card 3">
                <%= want.shop_name %>
              </a>
            </h3>
            <span class="block my-2 text-sm text-gray-600" datetime="2019-01-01"><span class="bg-gray-300 px-2 rounded mr-2">住所</span><%= want.address %></span>
            <p>
              <span class="bg-gray-300 px-2 rounded text-sm mr-2">メモ</span>
              <%= want.memo %>
            </p>
            <%= link_to user_want_path(current_user, want), method: :delete, data: { confirm: '削除して宜しいですか？' } do %>
            <span class="material-icons mt-2">
              delete
            </span>
            <% end %>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </section>
  </div>

app/views/wants/new.html.erb
<div id="main-content">
  <!-- menu -->
  <%= render 'partial/menu' %>

  <section>
    <h1 class="text-red-500 font-bold text-xl">行きたいお店を保存する</h1>
    <div class="md:p-12 flex flex-row flex-wrap">
      <%= form_with model: @want, url: user_wants_path(current_user), local: true, class: 'md:w-1/2-screen m-0 p-5 bg-white w-2/3 mx-auto tw-h-full' do |new_want| %>
      <%= render 'partial/validation_error_messages', model: @want %>

      <div class="text-lg text-indigo-900">行きたいお店を保存しておく</div>

      <div class="flex-col flex py-3">
        <%= new_want.label :shop_name, '店名(必須)', class: 'pb-2 text-gray-700 font-semibold' %>
        <%= new_want.text_field :shop_name, class: 'p-2 shadow rounded-lg bg-gray-100 outline-none focus:bg-gray-200' %>
      </div>

      <div class="flex-col flex py-3">
        <%= new_want.label :address, '住所(必須)', class: 'pb-2 text-gray-700 font-semibold' %>
        <%= new_want.text_field :address, class: 'p-2 shadow rounded-lg bg-gray-100 outline-none focus:bg-gray-200' %>
      </div>

      <div class="flex-col flex py-3">
        <%= new_want.label :memo, 'メモ', class: 'pb-2 text-gray-700 font-semibold' %>
        <%= new_want.text_area :comment, class: 'p-2 shadow rounded-lg bg-gray-100 outline-none focus:bg-gray-200 resize-none', rows: 3 %>
      </div>

      <div class="mt-3">
        <%= new_want.submit '保存する', class: 'p-3 bg-red-600 text-white w-full hover:bg-red-800 cursor-pointer' %>
      </div>
      <% end %>
    </div>
  </section>
</div>