config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # root
  root 'shops#index'

  # # redirect
  # get '/reviews' => redirect('/reviews/new')

  # google login
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i(create destroy)

  # mypage
  get 'mypage', to: 'users#mypage', as: :mypage

  # all shops
  get 'all', to: 'shops#all', as: :all_shops

  # search form page
  get 'search_form', to: 'shops#search_form', as: :search_form

  # search
  get 'search', to: 'shops#search', as: :search

  # new shop results page
  get 'new_shop_result', to: 'shops#new_shop_results', as: :new_shop_results

  # new shop form
  get 'new_form', to: 'shops#new_form', as: :new_form

  # add new shop & show shop detail
  resources :shops, only: %i(create show) do
    collection do
      get :search_result
    end
  end

  # new review form & add new review & delete review
  resources :reviews, only: %i(new create destroy)

  # wants list page
  resources :users do
    resources :wants, except: %i(edit show update)
  end
end

app/models/shop.rb
require 'http'

class Shop < ApplicationRecord
    class << self

    def search term
      HTTP.get('http://webservice.recruit.co.jp/hotpepper/gourmet/v1/', :params => { :key => ENV['API_KEY'], :name => term, :format => 'json' })
    end
  end

  def add_category category
    shops_categories << category
  end

  def delete_category category
    shops_categories.delete(category)
  end

  def has_category? category
    shops_categories.include?(category)
  end

  def add_payment payment
    shops_payments << payment
  end

  def delete_payment payment
    shops_payments.delete(payment)
  end

  def has_payment? payment
    shops_payments.include?(payment)
  end

  # carrierwave
  mount_uploader :shop_image, ShopImageUploader

  # relation
  has_many :shop_categories, dependent: :destroy
  has_many :shops_categories, through: :shop_categories, source: :category
  has_many :shop_payments, dependent: :destroy
  has_many :shops_payments, through: :shop_payments, source: :payment
  has_many :reviews, dependent: :destroy

  # validation
  def image_content_type
    extension = ['image/png', 'image/jpg', 'image/jpeg']
    errors.add(:shop_image, "の拡張子が間違っています") unless shop_image.content_type.in?(extension)
  end

  validates :shop_name, :address, :shop_image,
            presence: true
  validates :shop_name,
            length: { maximum: 50 }
  validates :address,
            format: { with: /.*[都道府県]/ }
  # shop_image validation
  validate :image_content_type
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  require 'json'
  skip_before_action :check_logged_in, only: %i(index all show search_result)
  # before_action :set_q, only: %i(index search)

  def index
    @shops = Shop.all.order(created_at: :desc).limit(8)
  end

  def all
    @shops = Shop.page(params[:page]).per(8).order(created_at: :desc)
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def search_form
  end

  def new_shop_results
  end

  def new_form
    @shop = Shop.new
    @shop_data = params[:shop]
  end


  def search
    search_word = params[:search]

    res = JSON.parse(Shop.search(search_word))
    @results = res['results']
    logger.debug(@results)

    render 'new_shop_results'
  end

  def create
    logger.debug('ここから')
    logger.debug(params)
    categories = Category.where(id: params[:Category][:category_name])
    payments = Payment.where(id: params[:Payment][:payment_name])

    shop = Shop.new(shop_params)

    if categories.exists?
      categories.size.times do |index|
        shop.add_category(categories[index])
      end
    end

    if payments.exists?
      payments.size.times do |index|
        shop.add_payment(payments[index])
      end
    end

    if shop.save
      redirect_to root_path, notice: '新規登録が完了しました'
      else
        render 'new_form'
    end
  end

  def search_result
    @shops = @q.result.page(params[:page]).per(8)

    render 'search'
  end

  private
  def shop_params
    params.require(:shop).permit(:shop_name, :address, :shop_image, :parking)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
  def check_review(review)
    if @current_user == review
      return true
    end
  end
end

app/views/shops/all.html.erb
  <div id="main-content">
    <!-- menu -->
    <%= render 'partial/menu' %>

    <!-- all shops -->
    <section class="mt-5">
      <h1 class="text-red-500 font-bold text-xl">すべてのお店</h1>
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-4 mt-5 mb-12">
        <article>
          <section class="mt-6 grid md:grid-cols-2 lg:grid-cols-4 gap-x-6 gap-y-8">
            <% @shops.each do |shop| %>
            <article class="bg-white group relative rounded-lg overflow-hidden shadow-lg hover:shadow-2xl transform duration-200">
              <div class="relative w-full h-80 md:h-64 lg:h-44">
                <%= image_tag shop.shop_image.url, class: 'w-full h-full object-center object-cover', alt: shop.shop_name %>
              </div>
              <div class="px-3 py-4">
                <h3 class="text-sm text-gray-500 pb-2">
                  <%= link_to shop_path(shop.id), class: 'bg-red-600 py-1 px-2 text-white rounded-lg' do %>
                  <span class="absolute inset-0"></span>
                  <%= shop.shop_name %>
                  <% end %>
                </h3>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <span class="material-icons" style="vertical-align: -5px;">
                    location_on
                  </span>
                  <%= shop.address %></p>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <span class="material-icons" style="vertical-align: -5px;">
                    payments
                  </span>
                  <% shop.shop_payments.each do |payment| %>
                  <span class="bg-gray-300 px-2 py-1 rounded"><%= payment.payment.payment_name %></span>
                  <% end %>
                </p>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <% shop.shop_categories.each do |category| %>
                  <span>#<%= category.category.category_name %></span>
                  <% end %>
                </p>
                <p class="w-32 text-red-500 text-center ml-auto hover:bg-gray-300">コメントを投稿</p>
              </div>
            </article>
            <% end %>
          </section>
          <%= paginate @shops %>
        </article>
      </div>
    </section>
  </div>

app/views/shops/index.html.erb
  <div id="main-content">
    <!-- menu -->
    <%= render 'partial/menu' %>

    <!-- what's new -->
    <section>
      <h1 class="text-red-500 font-bold text-xl">お知らせ</h1>
      <ul class="mt-5">
        <li>2022/3/2&nbsp;行きたいお店を保存する機能を実装しました。マイページからアクセスできます</li>
        <li>2022/3/1&nbsp;マイページからレビューを確認できるようになりました</li>
        <li>2022/3/1&nbsp;店名・住所からお店を検索できるようになりました</li>
        <li>2022/2/28&nbsp;レビューの削除機能を追加しました</li>
        <li>2022/2/27&nbsp;トップページに最近追加されたお店を表示するようにしました</li>
        <li>2022/2/24&nbsp;Googleアカウントでログインが出来るようになりました</li>
      </ul>
    </section>

    <!-- new shops -->
    <section class="mt-5">
      <h1 class="text-red-500 font-bold text-xl">新着</h1>
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-4 mt-5 mb-12">
        <article>
          <section class="mt-6 grid md:grid-cols-2 lg:grid-cols-4 gap-x-6 gap-y-8">
            <% @shops.each do |shop| %>
            <article class="bg-white group relative rounded-lg overflow-hidden shadow-lg hover:shadow-2xl transform duration-200">
              <div class="relative w-full h-80 md:h-64 lg:h-44">
                <%= image_tag shop.shop_image.url, class: 'w-full h-full object-center object-cover', alt: shop.shop_name %>
              </div>
              <div class="px-3 py-4">
                <h3 class="text-sm text-gray-500 pb-2">
                  <%= link_to shop_path(shop.id), class: 'bg-red-600 py-1 px-2 text-white rounded-lg' do %>
                  <span class="absolute inset-0"></span>
                  <%= shop.shop_name %>
                  <% end %>
                </h3>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <span class="material-icons" style="vertical-align: -5px;">
                    location_on
                  </span>
                  <%= shop.address %></p>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <span class="material-icons" style="vertical-align: -5px;">
                    payments
                  </span>
                  <% shop.shop_payments.each do |payment| %>
                  <span class="bg-gray-300 px-2 py-1 rounded"><%= payment.payment.payment_name %></span>
                  <% end %>
                </p>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <% shop.shop_categories.each do |category| %>
                  <span>#<%= category.category.category_name %></span>
                  <% end %>
                </p>
                <p class="w-32 text-red-500 text-center ml-auto hover:bg-gray-300">レビューを投稿</p>
              </div>
            </article>
            <% end %>
          </section>
        </article>
      </div>
    </section>
  </div>

app/views/shops/new_form.html.erb
<div id="main-content">
  <!-- menu -->
  <%= render 'partial/menu' %>

  <section>
    <h1 class="text-red-500 font-bold text-xl">新しいお店を追加する</h1>
    <div class="md:p-12 mt-5 lg:mt-0 flex flex-row flex-wrap">
      <%= form_with model: @shop, url: shops_path, local: true, class: 'lg:w-1/2 m-0 p-5 bg-white w-full mx-auto tw-h-full' do |new_shop| %>

      <div class="text-lg text-indigo-900">お店の基本情報を入力してください</div>

      <div class="flex-col flex py-3">
        <%= new_shop.label :shop_name, '店名(必須)', class: 'pb-2 text-gray-700 font-semibold' %>
        <%= new_shop.text_field :shop_name, value: @shop_data['name'], class: 'p-2 shadow rounded-lg bg-gray-100 outline-none focus:bg-gray-200' %>
      </div>

      <div class="flex-col flex py-3">
        <%= new_shop.label :address, '住所(必須)', class: 'pb-2 text-gray-700 font-semibold' %>
        <%= new_shop.text_field :address, value: @shop_data['address'], class: 'p-2 shadow rounded-lg bg-gray-100 outline-none focus:bg-gray-200' %>
      </div>

      <div class="flex-col flex py-3">
        <%= new_shop.label :address, '画像(必須)', class: 'pb-2 text-gray-700 font-semibold' %>
        <%= new_shop.file_field :shop_image, class: 'p-2 shadow rounded-lg bg-gray-100 outline-none focus:bg-gray-200' %>
      </div>

      <div class="mt-3">
        <h2 class="pb-2 text-gray-700 font-semibold">カテゴリー(複数選択可)</h2>
        <div class="lg:flex justify-start gap-3">
          <% Category.all.each.with_index do | category, i| %>
          <div class="form-check form-check-inline">
            <label>
              <%= check_box_tag 'Category[category_name][]', category.id, false, id:"id_contents_#{i}" %>
              <%= category.category_name %>
            </label>
          </div>
          <% end %>
        </div>
      </div>

      <div class="mt-3">
        <h2 class="pb-2 text-gray-700 font-semibold">利用可能な支払い手段(複数選択可)</h2>
        <div class="lg:flex justify-start gap-3">
          <% Payment.all.each.with_index do | payment, i| %>
          <div class="form-check form-check-inline">
            <label>
              <%= check_box_tag 'Payment[payment_name][]', payment.id, false, id:"id_contents_#{i}" %>
              <%= payment.payment_name %>
            </label>
          </div>
          <% end %>
        </div>
      </div>

      <div class="mt-3">
        <h2 class="pb-2 text-gray-700 font-semibold">駐車場</h2>
        <div><span class="border px-2 py-1 rounded" id="parking-value">0</span>&nbsp;台ほど駐車可能</div>
        <%= new_shop.range_field :parking, class: 'p-2 shadow rounded-lg bg-gray-100 outline-none focus:bg-gray-200 w-full mt-3', in: 0..30, step: 5, id: 'parking' %>
      </div>

      <div class="mt-3">
        <%= new_shop.submit '登録', class: 'p-3 bg-red-600 text-white w-full hover:bg-red-800 cursor-pointer' %>
      </div>
      <% end %>
    </div>
  </section>
</div>

app/views/shops/new_shop_results.html.erb
<div id="main-content">
  <!-- menu -->
  <%= render 'partial/menu' %>

  <section>
    <h1 class="text-red-500 font-bold text-xl"><%= @results['results_returned'] %>件の検索結果</h1>
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-4 mt-5 mb-12">
      <article>
        <section class="mt-6 grid md:grid-cols-2 lg:grid-cols-4 gap-x-6 gap-y-8">
          <% if @results['shop'] %>
          <% @results['shop'].each do |shop| %>
          <article class="bg-white group relative rounded-lg overflow-hidden shadow-lg hover:shadow-2xl transform duration-200">
            <div class="px-3 py-4">
              <h3 class="text-sm text-gray-500 pb-2">
                <%= link_to new_form_path(shop: shop), class: 'py-1 px-2' do %>
                <span class="absolute inset-0"></span>
                <%= shop['name'] %>
                <% end %>
              </h3>
            </div>
          </article>
          <% end %>
          <% else %>
          <p>検索結果は見つかりませんでした</p>
          <% end %>
        </section>
      </article>
    </div>
  </section>
</div>

app/views/shops/search.html.erb
  <div id="main-content">
    <!-- menu -->
    <%= render 'partial/menu' %>

    <!-- all shops -->
    <section class="mt-5">
      <h1 class="text-red-500 font-bold text-xl">検索結果</h1>
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-4 mt-5 mb-12">
        <article>
          <section class="mt-6 grid md:grid-cols-2 lg:grid-cols-4 gap-x-6 gap-y-8">
            <% @shops.each do |shop| %>
            <article class="bg-white group relative rounded-lg overflow-hidden shadow-lg hover:shadow-2xl transform duration-200">
              <div class="relative w-full h-80 md:h-64 lg:h-44">
                <%= image_tag shop.shop_image.url, class: 'w-full h-full object-center object-cover', alt: shop.shop_name %>
              </div>
              <div class="px-3 py-4">
                <h3 class="text-sm text-gray-500 pb-2">
                  <%= link_to shop_path(shop.id), class: 'bg-red-600 py-1 px-2 text-white rounded-lg' do %>
                  <span class="absolute inset-0"></span>
                  <%= shop.shop_name %>
                  <% end %>
                </h3>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <span class="material-icons" style="vertical-align: -5px;">
                    location_on
                  </span>
                  <%= shop.address %></p>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <span class="material-icons" style="vertical-align: -5px;">
                    payments
                  </span>
                  <% shop.shop_payments.each do |payment| %>
                  <span class="bg-gray-300 px-2 py-1 rounded"><%= payment.payment.payment_name %></span>
                  <% end %>
                </p>
                <p class="text-base font-semibold text-gray-900 group-hover:text-indigo-600 mt-2">
                  <% shop.shop_categories.each do |category| %>
                  <span>#<%= category.category.category_name %></span>
                  <% end %>
                </p>
                <p class="w-32 text-red-500 text-center ml-auto hover:bg-gray-300">コメントを投稿</p>
              </div>
            </article>
            <% end %>
          </section>
          <%= paginate @shops %>
        </article>
      </div>
    </section>
  </div>

app/views/shops/search_form.html.erb
  <div id="main-content" class="h-screen">
    <!-- menu -->
    <%= render 'partial/menu' %>

    <!-- search shop -->
    <section>
      <h1 class="text-red-500 font-bold text-xl">登録店舗検索</h1>
      <div class='flex items-center justify-center mt-10'>
        <%= form_with url: search_path, local: true, method: :get, class: 'w-full' do %>
        <div class="flex items-center lg:w-1/2 mx-auto bg-white rounded-lg " x-data="{ search: '' }">
          <div class="w-full">
            <%= text_field_tag 'search', nil, placeholder: '店名で検索', class: 'w-full px-4 py-1 text-gray-800 rounded-full focus:outline-none' %>
          </div>
          <div>
            <button type="submit" class="flex items-center bg-red-600 justify-center w-12 h-12 text-white rounded-r-lg" :class="(search.length > 0) ? 'bg-purple-500' : 'bg-gray-500 cursor-not-allowed'" :disabled="search.length == 0">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"></path>
              </svg>
            </button>
          </div>
        </div>
        <% end %>
      </div>
    </section>
  </div>

app/views/shops/show.html.erb
  <div id="main-content">
    <!-- menu -->
    <%= render 'partial/menu' %>

    <!-- shop detail -->
    <section class="mt-5">
      <h1 class="text-red-500 font-bold text-xl"><%= @shop.shop_name %></h1>
      <main class="flex items-center p-2 lg:p-10 lg:w-5/6 mx-auto h-full bg-white mt-5">
        <div class="border-t border-b pt-8 grid lg:grid-cols-2 gap-8">
          <div class="flex flex-col justify-start">
            <div class="flex flex-col w-full object-cover lg:h-4/6 justify-items-start border rounded-lg overflow-hidden" style="min-heigth:320px">
              <%= image_tag @shop.shop_image.url, class: 'w-full h-full object-cover', alt: @shop.shop_name %>
            </div>
          </div>
          <div class="flex flex-col">
            <div class="flex flex-col gap-4">
              <h1 class="capitalize text-2xl font-extrabold"><%= @shop.address %></h1>
              <h2 class="text-lg"><span class="material-icons" style="vertical-align: -4px;">
                  local_parking
                </span><%= @shop.parking %>台ほど駐車可能</h2>
              <h2 class="text-lg"><span class="material-icons" style="vertical-align: -4px;">
                  payment
                </span>
                <% @shop.shop_payments.each do |payment| %>
                <span class="bg-gray-300 px-2 py-1 rounded"><%= payment.payment.payment_name %></span>
                <% end %>
              </h2>
              <p class="text-lg text-gray-500	">
                <% @shop.shop_categories.each do |category| %>
                <span>#<%= category.category.category_name %></span>
                <% end %>
              </p>
              <% if current_user %>
              <div class="flex items-center justify-end gap-4 my-6">
                <%= link_to 'レビューを投稿', new_review_path(user: @current_user, shop: @shop), class: "bg-red-600 px-2 py-2 text-white rounded-lg text-center" %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </main>
      <!-- review -->
      <% if @shop.reviews.exists? %>
      <% @shop.reviews.each do |review| %>
      <div class="bg-white lg:w-5/6 mx-auto mt-5 rounded-lg p-3  flex flex-col justify-center items-center md:items-start shadow-lg mb-4">
        <div class="mr-auto lg:flex flex-row justify-center mr-2">
          <div class="flex">
            <%= image_tag review.user.image, class: 'rounded-full w-10 h-10 mr-4 shadow-lg mb-4', width: 48, height: 48, alt: review.user.name %>
            <h3 class="text-purple-600 font-semibold text-lg text-center md:text-left "><%= review.user.name %></h3>
          </div>
          <span class="ml-2 mt-1"><span class="bg-gray-300 px-2 rounded">予算</span>&nbsp;<%= review.price.to_s(:delimited) %>円</span>
          <span class="ml-2 mt-1"><span class="bg-gray-300 px-2 rounded">評価</span>&nbsp;<%= review.score %></span>
        </div>
        <p style="width: 90%" class="text-gray-600 text-lg mt-4 lg:mt-0"><%= review.comment %></p>
        <% if check_review(review.user) %>
        <%= link_to review_path(review), class: 'ml-auto', method: :delete, data: { confirm: 'レビューを削除して宜しいですか?' } do %>
        <span class="material-icons">
          delete
        </span>
        <% end %>
        <% end %>
      </div>
      <% end %>
      <% end %>
    </section>
  </div>