config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # root
  root 'shops#index'

  # # redirect
  # get '/reviews' => redirect('/reviews/new')

  # google login
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i(create destroy)

  # mypage
  get 'mypage', to: 'users#mypage', as: :mypage

  # all shops
  get 'all', to: 'shops#all', as: :all_shops

  # search form page
  get 'search_form', to: 'shops#search_form', as: :search_form

  # search
  get 'search', to: 'shops#search', as: :search

  # new shop results page
  get 'new_shop_result', to: 'shops#new_shop_results', as: :new_shop_results

  # new shop form
  get 'new_form', to: 'shops#new_form', as: :new_form

  # add new shop & show shop detail
  resources :shops, only: %i(create show) do
    collection do
      get :search_result
    end
  end

  # new review form & add new review & delete review
  resources :reviews, only: %i(new create destroy)

  # wants list page
  resources :users do
    resources :wants, except: %i(edit show update)
  end
end

app/models/user.rb
class User < ApplicationRecord
  class << self
    def find_or_create_from_auth_hash(auth_hash)
      user_params = user_params_from_auth_hash(auth_hash)
      find_or_create_by(email: user_params[:email]) do |user|
        user.update(user_params)
      end
    end

    private

    def user_params_from_auth_hash(auth_hash)
      {
        name: auth_hash.info.name,
        email: auth_hash.info.email,
        image: auth_hash.info.image,
      }
    end
  end

  # relation
  has_many :reviews, dependent: :destroy
  has_many :wants, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def mypage

  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/mypage.html.erb
<div id="main-content">
  <!-- menu -->
  <%= render 'partial/menu' %>

  <section>
    <h1 class="text-red-500 font-bold text-xl">マイページ</h1>
    <h2 class="text-red-500 text-lg mt-5">登録情報</h2>
    <span class="block">ユーザー名:&nbsp;<%= current_user.name %></span>
    <%= link_to '行きたいお店リスト', user_wants_path(current_user), class: 'bg-red-600 text-white p-2 rounded mt-5 inline-block' %>
    <h2 class="text-red-500 text-lg mt-5">投稿したレビュー</h2>
    <div id="menu" class="container px-4">
      <div class="flex flex-wrap mt-6 justify-start">
        <% if current_user.reviews.exists? %>
        <% current_user.reviews.each do |review| %>
        <div class="mt-3 grid grid-cols-1 sm:grid-cols-6 md:grid-cols-6 lg:grid-cols-6 xl:grid-cols-6 gap-4">
          <div class="col-span-2 sm:col-span-1 xl:col-span-1">
            <%= link_to image_tag(review.shop.shop_image.url, class: 'h-24 w-24 rounded mx-auto'), shop_path(review.shop) %>
          </div>
          <div class="mt-3 col-span-2 sm:col-span-4 xl:col-span-4">
            <span class="mt-1"><span class="bg-gray-300 px-2 rounded">予算</span>&nbsp;<%= review.price.to_s(:delimited) %>円</span>
            <span class="ml-2 mt-1"><span class="bg-gray-300 px-2 rounded">評価</span>&nbsp;<%= review.score %></span>
            <p>
              <%= review.comment %>
            </p>
          </div>
        </div>
        <% end %>
        <% end %>
      </div>
    </div>
  </section>
</div>