config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # root
  root 'shops#index'

  # # redirect
  # get '/reviews' => redirect('/reviews/new')

  # google login
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: %i(create destroy)

  # mypage
  get 'mypage', to: 'users#mypage', as: :mypage

  # all shops
  get 'all', to: 'shops#all', as: :all_shops

  # search form page
  get 'search_form', to: 'shops#search_form', as: :search_form

  # search
  get 'search', to: 'shops#search', as: :search

  # new shop results page
  get 'new_shop_result', to: 'shops#new_shop_results', as: :new_shop_results

  # new shop form
  get 'new_form', to: 'shops#new_form', as: :new_form

  # add new shop & show shop detail
  resources :shops, only: %i(create show) do
    collection do
      get :search_result
    end
  end

  # new review form & add new review & delete review
  resources :reviews, only: %i(new create destroy)

  # wants list page
  resources :users do
    resources :wants, except: %i(edit show update)
  end
end

app/views/partial/_header.html.erb
<nav class="flex relative items-center justify-between flex-wrap bg-white py-4 lg:px-12 border-solid bg-red-600 text-white">
  <div class="flex justify-between lg:w-auto w-full lg:border-b-0 pl-6 pr-6 lg:pr-2 border-solid border-b-2 border-gray-300 pb-5 lg:pb-0">
    <div class="flex items-center flex-shrink-0 mx-auto lg:mr-0">
      <span class="font-semibold text-3xl tracking-tight" style="font-family: 'Reggae One', cursive;"><%= link_to 'PAIMESHI!!', root_path %></span>
    </div>
    <div class="block lg:hidden order-first">
      <button id="nav" class="flex items-center px-3 py-2 border-2 rounded text-white border-white menu-button-sp">
        <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
          <title>Menu</title>
          <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
        </svg>
      </button>
    </div>
    <div class="block lg:hidden order-last">
      <div>
        <span class="material-icons border-4 rounded-full cursor-pointer google-login-button">
          account_circle
        </span>
      </div>
    </div>
  </div>
  <div class="menu-sp w-full hidden flex-grow lg:flex lg:items-center lg:w-auto lg:px-3 px-8">
    <div class="text-md font-bold lg:flex-grow">
      <%= link_to '一覧', all_shops_path, class: 'block lg:hidden mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-gray-700 mr-2' %>
      <%= link_to 'お店を登録', search_form_path, class: 'block lg:hidden lg:mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-gray-700 mr-2' %>
    </div>
  </div>
  <!-- This is an example component -->
  <div class="relative mx-auto text-gray-600 hidden lg:block">
    <%= search_form_for @q, url: search_result_shops_path, class: 'lg:hidden' do |search| %>
    <%= search.text_field :shop_name_or_address_cont, class: 'border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none', placeholder: '店名・住所' %>
    <button type="submit" class="absolute right-0 top-0 mt-3 mr-2">
      <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
        <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
      </svg>
    </button>
    <% end %>
  </div>
  </div>
  <div class="relative w-full px-2 mt-3 mx-auto text-gray-600 lg:hidden">
    <%= search_form_for @q, url: search_result_shops_path do |search| %>
    <%= search.text_field :shop_name_or_address_cont, class: 'border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none w-full', placeholder: '店名・住所' %>
    <button type="submit" class="absolute right-0 top-0 mt-3 mr-5">
      <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
        <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
      </svg>
    </button>
    <% end %>
  </div>

  <div class="menu w-full lg:block hidden flex-grow lg:flex lg:items-center lg:w-auto lg:px-3 px-8">
    <div class="text-md font-bold lg:flex-grow">
      <%= link_to '一覧', all_shops_path, class: 'block mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-gray-700 mr-2' %>
      <%= link_to 'お店を登録', search_form_path, class: 'block mt-4 lg:inline-block lg:mt-0 hover:text-white px-4 py-2 rounded hover:bg-gray-700 mr-2' %>
    </div>
    <!-- This is an example component -->
    <div class="relative mx-auto text-gray-600 lg:block">
      <%= search_form_for @q, url: search_result_shops_path do |search| %>
      <%= search.text_field :shop_name_or_address_cont, class: 'border-2 border-gray-300 bg-white h-10 pl-2 pr-8 rounded-lg text-sm focus:outline-none', placeholder: '店名・住所' %>
      <button type="submit" class="absolute right-0 top-0 mt-3 mr-2">
        <svg class="text-gray-600 h-4 w-4 fill-current" xmlns="http://www.w3.org/2000/svg" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 56.966 56.966" style="enable-background:new 0 0 56.966 56.966;" xml:space="preserve" width="512px" height="512px">
          <path d="M55.146,51.887L41.588,37.786c3.486-4.144,5.396-9.358,5.396-14.786c0-12.682-10.318-23-23-23s-23,10.318-23,23  s10.318,23,23,23c4.761,0,9.298-1.436,13.177-4.162l13.661,14.208c0.571,0.593,1.339,0.92,2.162,0.92  c0.779,0,1.518-0.297,2.079-0.837C56.255,54.982,56.293,53.08,55.146,51.887z M23.984,6c9.374,0,17,7.626,17,17s-7.626,17-17,17  s-17-7.626-17-17S14.61,6,23.984,6z" />
        </svg>
      </button>
      <% end %>
    </div>
    <div class="ml-5">
      <span class="material-icons border-4 rounded-full google-login-button cursor-pointer">
        account_circle
      </span>
    </div>
  </div>
</nav>

app/views/partial/_menu.html.erb
<ul class="fixed bg-gray-300 p-3 rounded cursor-pointer right-5 top-20 hidden google-login z-10 <%= 'w-36' if current_user %>">
  <% if current_user %>
  <li><%= link_to 'My Page', mypage_path, class: 'hover:underline' %></li>
  <li class="mt-2"><%= link_to 'Sign out', log_out_path %></li>
  <% else %>
  <li><%= link_to 'Login with Google', '/auth/google_oauth2', method: :post, class: 'hover:underline' %></li>
  <% end %>
</ul>

app/views/partial/_review_error_messages.html.erb
<% if @review.errors.any? %>
<div class="alert alert-warning">
  <ul class="bg-red-600 text-white p-2 text-center">
    <% @review.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/partial/_validation_error_messages.html.erb
<% if model.errors.any? %>
<div class="alert alert-warning">
  <ul class="bg-red-600 text-white p-2 text-center">
    <% model.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>